import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
test('rejection enforces identity, freshness, merged-state safety and branch ownership',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'lives-review-test-')),file=join(dir,'event.json'),source=await readFile(new URL('./review-command.mjs',import.meta.url),'utf8');const savedFetch=globalThis.fetch,savedPath=process.env.GITHUB_EVENT_PATH,savedToken=process.env.GH_TOKEN;
 try{process.env.GITHUB_EVENT_PATH=file;process.env.GH_TOKEN='isolated-test-token';
 for(const mode of ['allowed','wrong-user','edited','merged','foreign-branch','changed-branch']){
  const user={id:282984756},event={repository:{full_name:'Bhav3shChawla/lives-on.dev'},action:'created',sender:user,comment:{id:1,user,body:'/rejected',created_at:'2026-09-08T12:00:00Z',updated_at:'2026-09-08T12:00:00Z'},issue:{number:2,pull_request:{}}};if(mode==='wrong-user')event.sender={id:3};await writeFile(file,JSON.stringify(event));const writes=[];
  globalThis.fetch=async(url,options={})=>{const path=new URL(url).pathname,method=options.method||'GET';if(method!=='GET')writes.push({path,method});let data={};if(path.endsWith('/issues/comments/1'))data={...event.comment,...(mode==='edited'?{updated_at:'2026-09-08T12:01:00Z'}:{})};else if(path.endsWith('/pulls/2'))data={merged:mode==='merged',base:{repo:{full_name:'Bhav3shChawla/lives-on.dev'},ref:'main'},head:{repo:{full_name:mode==='foreign-branch'?'other/repo':'Bhav3shChawla/lives-on.dev'},ref:'requests/123/test/r1-swap',sha:'a'.repeat(40)}};else if(path.includes('/git/ref/heads/'))data={object:{sha:(mode==='changed-branch'?'b':'a').repeat(40)}};return method==='DELETE'?new Response(null,{status:204}):Response.json(data);};
  const run=()=>import('data:text/javascript;base64,'+Buffer.from('// '+mode+'\n'+source).toString('base64'));
  if(['wrong-user','edited','merged'].includes(mode)){await assert.rejects(run);assert.equal(writes.length,0);}else{await run();assert.ok(writes.some(w=>w.method==='PATCH'));assert.equal(writes.some(w=>w.method==='DELETE'),mode==='allowed');}
 }
 }finally{globalThis.fetch=savedFetch;if(savedPath===undefined)delete process.env.GITHUB_EVENT_PATH;else process.env.GITHUB_EVENT_PATH=savedPath;if(savedToken===undefined)delete process.env.GH_TOKEN;else process.env.GH_TOKEN=savedToken;await rm(dir,{recursive:true,force:true});}
});
